---
mount__host_binds:

  # nfs mount -> transmission watch dir
  - src: '/mnt/nfs/ptp_seed'
    dest: '/var/lib/transmission-daemon/downloads'
    fstype: 'none'
    state: 'present'
    opts:
    - 'bind'
    - 'x-systemd.automount'
    - 'x-systemd.requires-mounts-for=/mnt/nfs/ptp_seed/'



