resources__host_files:

  # tranmission settings
  - src: '{{ resources__src + ansible_hostname + "/etc/transmission-daemon/settings.json" }}'
    dest: '/etc/transmission-daemon/settings.json'
    owner: 'debian-transmission'
    group: 'debian-transmission'
    mode: '0600'
    state: 'present'

  # ptp archiver script
  - src: '{{ resources__src + ansible_hostname + "/var/lib/transmission-daemon/archiver.py" }}'
    dest: '/var/lib/transmission-daemon/archiver.py'
    owner: 'debian-transmission'
    group: 'debian-transmission'
    mode: '0700'
    state: 'present'


