---
mount__host_devices:

  # deluge seed volume (mdadm raid)
  - src: 'uuid=aaa707bf-f12f-4ed0-9a19-24dea0f424c9'
    path: '/mnt/vols/deluge'
    fstype: 'ext4'
    options: [ 'defaults' ]
    dump: '0'
    passno: '2'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0770'
    state: 'present'
