---
resources__host_paths:

  # remove deluged init.d script
  - path: '/etc/init.d/deluged'
    state: 'absent'

  # remove deluged etc/default init.d conf
  - path: '/etc/default/deluged'
    state: 'absent'

  # remove default pid file location
  - path: '/var/lib/deluged/config/deluged/deluged.pid'
    state: 'absent'

  # remove deluge default config parent dir
  - path: '/var/lib/deluged/.config'
    state: 'absent'

  # create root mount dirs
  - path: '/mnt'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  - path: '/mnt/nfs'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  - path: '/mnt/vols'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  # create deluge pid dir
  - path: '/var/run/deluged'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0750'
    state: 'directory'

  # create deluge lib dir
  - path: '/var/lib/deluged'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0750'
    state: 'directory'

  # create deluged config dir
  - path: '/var/lib/deluged/config/deluge-web'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0750'
    state: 'directory'

  # create deluged config dir
  - path: '/var/lib/deluged/config/deluged'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0750'
    state: 'directory'

  # create deluged watch dir
  - path: '/var/lib/deluged/config/deluged/watch'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0750'
    state: 'directory'

  # create deluged archive dir
  - path: '/var/lib/deluged/config/deluged/torrent_files'
    owner: 'debian-deluged'
    group: 'debian-deluged'
    mode: '0750'
    state: 'directory'

  # create deluge log dir
  - path: '/var/log/deluged'
    owner: 'debian-deluged'
    group: 'adm'
    mode: '2750'
    state: 'directory'

  # set perms on deluged log file
  - path: '/var/log/deluged/deluged.log'
    owner: 'debian-deluged'
    group: 'adm'
    mode: '0640'
    state: 'touch'

  # set perms on deluge-web log file
  - path: '/var/log/deluged/deluge-web.log'
    owner: 'debian-deluged'
    group: 'adm'
    mode: '0640'
    state: 'touch'

resources__host_files:

  # deluged systemd script
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system/deluged.service" }}'
    dest: '/etc/systemd/system/deluged.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

  # deluge-web systemd script
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system/deluge-web.service" }}'
    dest: '/etc/systemd/system/deluge-web.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

  # deluged var run directory
  - src: '{{ resources__src + ansible_hostname + "/etc/tmpfiles.d/var_run_deluged.conf" }}'
    dest: '/etc/tmpfiles.d/var_run_deluged.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

resources__host_commands:

  # reload systemd daemon
  - name: 'reload the systemd daemon'
    shell: |
      sleep 2 && systemctl daemon-reload && sleep 2

