---
nfs__host_shares:

## TRUENAS NZBGET
  - path: '/mnt/nfs/nzbget'
    src: '10.10.70.20:/mnt/tank03/ds01/media/.downloads/nzbget'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd }}"
    owner: 'fclaude'
    group: 'labmedia'
    mode: '0770'
    state: 'present'
