---
nfs__host_shares:

## truenas icloud downloader
  - path: '/mnt/nfs/icloud_downloader'
    src: '10.69.69.1:/mnt/tank03/ds03/backups/media/photos/icloud_photos/icloud_downloader'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd }}"
    owner: 'fclaude'
    group: 'labmedia'
    mode: '0755'
    state: 'present'

## truenas icloud downloader (archive directory)
  - path: '/mnt/nfs/icloud_downloader_archive'
    src: '10.69.69.1:/mnt/tank03/ds03/backups/media/photos/icloud_photos/archive'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd }}"
    owner: 'fclaude'
    group: 'labmedia'
    mode: '0755'
    state: 'present'
