---
nfs__default_mount_type: 'nfs4'

# nfs option global variables
nfs_opts:

  # defaults for read/write shares
  def_rw:
    - 'rw'
    - 'vers=4'
    - 'proto=tcp'
    - 'port=2049'
    - 'minorversion=1'
    - '_netdev'
    - 'hard'
    - 'intr'
    - 'auto'
    - 'timeo=600'    # default
    - 'retrans=2'    # default

  # defaults for read only shares
  def_ro:
    - 'ro'
    - 'vers=4'
    - 'proto=tcp'
    - 'port=2049'
    - 'minorversion=1'
    - '_netdev'
    - 'hard'
    - 'intr'
    - 'auto'
    - 'timeo=600'    # default
    - 'retrans=2'    # default
    - 'nocto'

  # defaults for all shares
  safety:
    - 'nosuid'
    - 'nodev'
    - 'noexec'

  # defaults when using systemd automount
  systemd:
    - 'x-systemd.automount'
    - 'x-systemd.idle-timeout=1h'

  systemd_med_timeo:
    - 'x-systemd.automount'
    - 'x-systemd.idle-timeout=6h'

  systemd_long_timeo:
    - 'x-systemd.automount'
    - 'x-systemd.idle-timeout=12h'

  systemd_no_timeo:
    - 'x-systemd.automount'
