---
users__host_accounts:

  - name: 'sandbox'
    group: 'sandbox'
    append: True
    user: True
    admin: False
    uid: '2000'
    gid: '2000'
    comment: 'sandbox acct'
    update_password: 'always'
    linger: False
    state: 'present'
    home: '/home/sandbox'
    home_owner: 'sandbox'
    home_group: 'sandbox'
    home_mode: '0700'
    create_home: True
    move_home: True
    generate_ssh_key: False
    sshkeys: "{{ ssh_auth_keys_debops.fclaude_user }}"
    sshkeys_exclusive: True
    sshkeys_state: 'present'
    shell: '/bin/bash'
    dotfiles_enabled: False
