---
resources__host_paths:

  - path: '/home/fclaude/.config'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0700'
    state: 'directory'

  - path: '/home/fclaude/.config/urlwatch'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0700'
    state: 'directory'

  - path: '/home/fclaude/.local'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0700'
    state: 'directory'

  - path: '/home/fclaude/.local/share'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0700'
    state: 'directory'

  - path: '/home/fclaude/.local/share/urlwatch'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0700'
    state: 'directory'

  - path: '/home/fclaude/.local/share/urlwatch/examples'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0700'
    state: 'directory'

resources__host_files:

## urlwatch configuration file

  - src: '{{ resources__src + ansible_hostname + "/home/fclaude/dot_config/urlwatch/urlwatch.yaml" }}'
    dest: '/home/fclaude/.config/urlwatch/urlwatch.yaml'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0600'
    state: 'present'

## urlwatch configuration file (original)

  - src: '{{ resources__src + ansible_hostname + "/home/fclaude/dot_config/urlwatch/urlwatch.yaml.original" }}'
    dest: '/home/fclaude/.config/urlwatch/urlwatch.yaml.original'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0400'
    state: 'present'

## urlwatch url watchlist

  - src: '{{ resources__src + ansible_hostname + "/home/fclaude/dot_config/urlwatch/urls.yaml" }}'
    dest: '/home/fclaude/.config/urlwatch/urls.yaml'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0600'
    state: 'present'

## urlwatch url watchlist (original)

  - src: '{{ resources__src + ansible_hostname + "/home/fclaude/dot_config/urlwatch/urls.yaml.original" }}'
    dest: '/home/fclaude/.config/urlwatch/urls.yaml.original'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0400'
    state: 'present'

## urlwatch hooks default examples (original)

  - src: '{{ resources__src + ansible_hostname + "/home/fclaude/dot_local/share/urlwatch/examples/hooks.py.example.original" }}'
    dest: '/home/fclaude/.local/share/urlwatch/examples/hooks.py.example.original'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0400'
    state: 'present'

## urlwatch urls default examples (original)

  - src: '{{ resources__src + ansible_hostname + "/home/fclaude/dot_local/share/urlwatch/examples/urls.yaml.example.original" }}'
    dest: '/home/fclaude/.local/share/urlwatch/examples/urls.yaml.example.original'
    owner: 'fclaude'
    group: 'fclaude'
    mode: '0400'
    state: 'present'
