---
resources__host_paths: []

resources__host_files:

  # jackett systemd script
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system/jackett.service" }}'
    dest: '/etc/systemd/system/jackett.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

resources__host_archives:

  # jackett binaries
  - src: '{{ resources__src + ansible_hostname + "/jackett.binaries.linuxamdx64.tar.gz" }}'
    dest: '/opt/'
    creates: '/opt/jackett'
    owner: 'jackett'
    group: 'jackett'
