---
mount__host_binds:

  # import bind mounts
  - src: '/mnt/nfs/syncthing/syncthing_server'
    dest: '/var/lib/syncthing/syncthing_server'
    state: 'present'
    fstype: 'none'
    opts:
      - 'bind'
      - '_netdev'
      - 'x-systemd.automount'
      - 'x-systemd.requires-mounts-for=/mnt/nfs/syncthing/syncthing_server'
