---
resources__host_paths:

  # remove default syncthing-resume systemd service file
  - dest: '/lib/systemd/system/syncthing-resume.service'
    state: 'absent'

  # remove default syncthing-resume systemd service file
  - dest: '/lib/systemd/system/syncthing@.service'
    state: 'absent'

  # delete syncthing default sync dir
  - path: '/var/lib/syncthing/sync'
    state: 'absent'

  # create root mount dirs
  - path: '/mnt'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  - path: '/mnt/nfs'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  # syncthing config dir
  - path: '/etc/syncthing'
    owner: 'sthing'
    group: 'sthing'
    mode: '0700'
    state: 'directory'

  # syncthing log dir
  - path: '/var/log/syncthing'
    owner: 'sthing'
    group: 'adm'
    mode: '2750'
    state: 'directory'

  # syncthing log file
  - path: '/var/log/syncthing/syncthing.log'
    owner: 'sthing'
    group: 'sthing'
    mode: '0640'
    state: 'touch'

  # syncthing home dir
  - path: '/var/lib/syncthing'
    owner: 'sthing'
    group: 'sthing'
    mode: '0750'
    state: 'directory'

  # syncthing data dir
  - path: '/var/lib/syncthing/data'
    owner: 'sthing'
    group: 'sthing'
    mode: '0700'
    state: 'directory'

  # syncthing sync server dir
  - path: '/var/lib/syncthing/syncthing_server'
    owner: 'sthing'
    group: 'sthing'
    mode: '0750'
    state: 'directory'

  # syncthing nfs root
  - path: '/mnt/nfs'
    owner: 'sthing'
    group: 'sthing'
    mode: '0755'
    state: 'directory'

resources__host_files:

  # syncthing systemd service file
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system/syncthing.service" }}'
    dest: '/etc/systemd/system/syncthing.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

  # syncthing-resume systemd service file
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system/syncthing-resume.service" }}'
    dest: '/etc/systemd/system/syncthing-resume.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

resources__host_commands:

  # reload systemd daemon
  - name: 'reload the systemd daemon'
    shell: |
      sleep 2 && systemctl daemon-reload && sleep 2