---
ferm__host_rules:

  - name: 'DEBOPS_accept_archbtw_80_pihole_tcp'
    type: 'accept'
    accept_any: False
    saddr: '10.10.100.10'
    daddr: '10.10.70.10'
    dport: '80'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from archbtw to pihole port 80/tcp'

  - name: 'DEBOPS_accept_mbp_80_pihole_tcp'
    type: 'accept'
    accept_any: False
    saddr: '10.10.100.20'
    daddr: '10.10.70.10'
    dport: '80'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from mbp to pihole port 80/tcp'

  - name: 'DEBOPS_accept_any_53_pihole_tcp'
    type: 'accept'
    accept_any: True
    daddr: '10.10.70.10'
    dport: '53'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from any to pihole port 53/tcp'

  - name: 'DEBOPS_accept_any_53_pihole_udp'
    type: 'accept'
    accept_any: True
    daddr: '10.10.70.10'
    dport: '53'
    protocol: 'udp'
    rule_state: 'present'
    comment: 'accept incoming connections from any to pihole port 53/udp'

  - name: 'DEBOPS_reject_any_443_tcp'
    type: 'accept'
    accept_any: False
    dport: '443'
    protocol: 'tcp'
    target: 'REJECT'
    reject_with: 'tcp-reset'
    rule_state: 'present'
    comment: 'reject incoming connections from any to pihole port 443/tcp'

  - name: 'DEBOPS_reject_any_80_udp'
    type: 'accept'
    accept_any: False
    dport: '80'
    protocol: 'udp'
    target: 'REJECT'
    reject_with: 'icmp-port-unreachable'
    rule_state: 'present'
    comment: 'reject incoming connections from any to pihole port 80/udp'

  - name: 'DEBOPS_reject_any_443_udp'
    type: 'accept'
    accept_any: False
    dport: '443'
    protocol: 'udp'
    target: 'REJECT'
    reject_with: 'icmp-port-unreachable'
    rule_state: 'present'
    comment: 'reject incoming connections from any to pihole port 443/udp'

