---
ferm__host_rules:

  # sonarr webui port archbtw
  - name: 'DEBOPS_accept_archbtw_8989_sonarr_webui_tcp'
    type: 'accept'
    accept_any: False
    saddr: '10.10.100.10'
    daddr: '10.10.120.25'
    dport: '8989'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from archbtw to port 8989/tcp'

  # sonarr webui port mbp
  - name: 'DEBOPS_accept_mbp_8989_sonarr_webui_tcp'
    type: 'accept'
    accept_any: False
    saddr: '10.10.100.20'
    daddr: '10.10.120.25'
    dport: '8989'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from mbp to port 8989/tcp'

  # sonarr webui port marion_rr
  - name: 'DEBOPS_accept_marionRR_8989_sonarr_webui_tcp'
    type: 'accept'
    accept_any: False
    saddr: '10.117.45.2'
    daddr: '10.10.120.25'
    dport: '8989'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from marionRR to port 8989/tcp'
