---
ferm__host_rules:

  # rtps torrent port (tcp)
  - name: 'DEBOPS_accept_any_58583_rtorrent_tcp'
    type: 'accept'
    accept_any: True
    daddr: '10.10.90.10'
    dport: '58583'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from any to port 58583/tcp'

  # rtps torrent port (udp) ## disabled
  - name: 'DEBOPS_accept_any_58583_rtorrent_udp'
    type: 'accept'
    accept_any: True
    daddr: '10.10.90.10'
    dport: '58583'
    protocol: 'udp'
    rule_state: 'absent'
    comment: 'accept incoming connections from any to port 58583/udp'
