---
resources__host_paths:

# remove

  - path: '/home/rtorrent/.local/profile.d'
    state: 'absent'

  - path: '/home/rtorrent/.local/profile.d/rt-alias.sh'
    state: 'absent'

  - path: '/home/rtorrent/.bash_aliases'
    state: 'absent'

  - path: '/etc/nginx/sites-enabled/localhost.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-available/localhost.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-enabled/welcome.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-available/welcome.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-enabled/default'
    state: 'absent'

  - path: '/etc/nginx/sites-available/default'
    state: 'absent'

# touch

  # pyrotorque trigger
  - path: '/home/rtorrent/.pyroscope/run/pyrotorque'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0400'
    state: 'touch'

  # rt_work
  - path: '/mnt/vols/rt_work/.mounted'
    owner: 'rtorrent'
    group: 'rtorrent'
    mode: '0400'
    state: 'touch'

  # rt_share
  - path: '/mnt/vols/rt_share/.mounted'
    owner: 'rtorrent'
    group: 'rtorrent'
    mode: '0400'
    state: 'touch'

# root mount dirs

  # mnt
  - path: '/mnt'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  # nfs
  - path: '/mnt/nfs'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  # vols
  - path: '/mnt/vols'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'


# mount dot files (checked by rtps start script at runtime)

    # nfs rt_watch
  # - path: '/mnt/nfs/rt_watch/.mounted'
  #   state: 'touch'

    # nfs rt_share
  # - path: '/mnt/nfs/rt_share/.mounted'
  #   state: 'touch'

    # nfs books
  # - path: '/mnt/nfs/books/.mounted'
  #   state: 'touch'

    # nfs music
  # - path: '/mnt/nfs/music/.mounted'
  #   state: 'touch'

    # nfs pr0n
  # - path: '/mnt/nfs/pr0n/.mounted'
  #   state: 'touch'

    # nfs tv
  # - path: '/mnt/nfs/tv/.mounted'
  #   state: 'touch'

    # nfs discs
  # - path: '/mnt/nfs/discs/.mounted'
  #   state: 'touch'

    # nfs docs
  # - path: '/mnt/nfs/docs/.mounted'
  #   state: 'touch'

    # nfs french
  # - path: '/mnt/nfs/french/.mounted'
  #   state: 'touch'

    # nfs movies
  # - path: '/mnt/nfs/movies/.mounted'
  #   state: 'touch'

    # nfs shred
  # - path: '/mnt/nfs/shred/.mounted'
  #   state: 'touch'

    # nfs uhd
  # - path: '/mnt/nfs/uhd/.mounted'
  #   state: 'touch'

    # nfs uhd docs
  # - path: '/mnt/nfs/uhd_docs/.mounted'
  #   state: 'touch'

    # nfs uhd tv
  # - path: '/mnt/nfs/uhd_tv/.mounted'
  #   state: 'touch'


resources__host_files:

# rtps home configs

  # tmux
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtps-tmux" }}'
    dest: '/home/rtorrent/.tmux.conf'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0600'
    state: 'present'

  # dot profile
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtps-profile" }}'
    dest: '/home/rtorrent/.profile'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0600'
    state: 'present'

  # dot bashrc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtps-bashrc" }}'
    dest: '/home/rtorrent/.bashrc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0600'
    state: 'present'

  # dot bash completion
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtps-bash_completion" }}'
    dest: '/home/rtorrent/.bash_completion'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0640'
    state: 'present'

  # rtps aliases
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtps-aliases" }}'
    dest: '/home/rtorrent/.rtps-aliases'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0600'
    state: 'present'


# systemd

  # system limits (absent)
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system.conf.d/systemd-system-limits.conf" }}'
    dest: '/etc/systemd/system.conf.d/systemd-system-limits.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'absent'

  # user limits (absent)
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/user.conf.d/systemd-user-limits.conf" }}'
    dest: '/etc/systemd/user.conf.d/systemd-user-limits.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'


# nginx

  # rtps nginx server
  - src: '{{ resources__src + ansible_hostname + "/etc/nginx/sites-available/rtps.conf" }}'
    dest: '/etc/nginx/sites-available/rtps.conf'
    owner: 'root'
    group: 'root'
    mode: '0400'
    state: 'present'


# etc

  # security/nofile
  - src: '{{ resources__src + ansible_hostname + "/etc/security/limits.d/rtorrent-nofile.conf" }}'
    dest: '/etc/security/limits.d/rtorrent-nofile.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'

  # security/nproc
  - src: '{{ resources__src + ansible_hostname + "/etc/security/limits.d/rtorrent-nproc.conf" }}'
    dest: '/etc/security/limits.d/rtorrent-nproc.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'


# rtps scripts

  # rtuptime
  - src: '{{ resources__src + ansible_hostname + "/rtps-scripts/rtuptime" }}'
    dest: '/home/rtorrent/bin/rtuptime'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0750'
    state: 'present'


# pyroscope config files

  # bash-completion
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/bash-completion" }}'
    dest: '/home/rtorrent/.pyroscope/bash-completion'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # bash-completion (default)
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/bash-completion.default" }}'
    dest: '/home/rtorrent/.pyroscope/bash-completion.default'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # config.ini
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/config.ini" }}'
    dest: '/home/rtorrent/.pyroscope/config.ini'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0640'
    state: 'present'

  # config.ini (default)
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/config.ini.default" }}'
    dest: '/home/rtorrent/.pyroscope/config.ini.default'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # rtorrent-pyro
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/rtorrent-pyro.rc" }}'
    dest: '/home/rtorrent/.pyroscope/rtorrent-pyro.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # rtorrent-pyro (default)
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/rtorrent-pyro.rc.default" }}'
    dest: '/home/rtorrent/.pyroscope/rtorrent-pyro.rc.default'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # torque.ini
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/torque.ini" }}'
    dest: '/home/rtorrent/.pyroscope/torque.ini'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # torque.ini (default)
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/dot_pyroscope/torque.ini.default" }}'
    dest: '/home/rtorrent/.pyroscope/torque.ini.default'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'


# rtorrent configs

  # _rtolocal.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/_rtlocal.rc" }}'
    dest: '/home/rtorrent/rtorrent/_rtlocal.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # rtorrent.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # _rutorrent.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/_rutorrent.rc" }}'
    dest: '/home/rtorrent/rtorrent/_rutorrent.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # start
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/start" }}'
    dest: '/home/rtorrent/rtorrent/start'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0744'
    state: 'present'


# rtorrent.d

  # 00-pyrocore.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/00-pyrocore.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/00-pyrocore.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 05-rt-ps-columns.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/05-rt-ps-columns.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/05-rt-ps-columns.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 05-rt-ps-columns.rc.include
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/05-rt-ps-columns.rc.include" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/05-rt-ps-columns.rc.include'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 05-rt-ps-columns-v2.rc.include
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/05-rt-ps-columns-v2.rc.include" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/05-rt-ps-columns-v2.rc.include'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 10-instance-layout.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/10-instance-layout.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/10-instance-layout.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 15-logging.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/15-logging.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/15-logging.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 20-host-var-settings.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/20-host-var-settings.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/20-host-var-settings.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 20-session-name.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/20-session-name.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/20-session-name.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 30-resources.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/30-resources.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/30-resources.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 50-peers.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/50-peers.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/50-peers.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 50-port-binding.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/50-port-binding.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/50-port-binding.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # 50-trackers.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/50-trackers.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/50-trackers.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # autolabel-categories.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/autolabel-categories.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/autolabel-categories.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # bash-completion-handlers.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/bash-completion-handlers.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/bash-completion-handlers.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # curl-options.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/curl-options.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/curl-options.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # disable-control-q.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/disable-control-q.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/disable-control-q.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # network-history.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/network-history.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/network-history.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # start-nocron.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/start-nocron.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/start-nocron.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # tracker-aliases.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/tracker-aliases.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/tracker-aliases.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # views.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/views.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/views.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # watch-dirs.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/watch-dirs.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/watch-dirs.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # watch-dirs.rc.include
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/watch-dirs.rc.include" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/watch-dirs.rc.include'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

  # watch-disk-space.rc
  - src: '{{ resources__src + ansible_hostname + "/home/rtorrent/rtorrent/rtorrent.d/watch-disk-space.rc" }}'
    dest: '/home/rtorrent/rtorrent/rtorrent.d/watch-disk-space.rc'
    owner: 'rtorrent'
    group: 'rtxmlrpc'
    mode: '0644'
    state: 'present'

resources__host_commands:

  # reload systemd
  - name: 'reload the systemd daemon'
    shell: |
      sleep 2 && systemctl daemon-reload && sleep 2


  # reexec systemd
  - name: 'running systemd daemon-reexec'
    shell: |
      sleep 2 && systemctl daemon-reexec && sleep 2


  # enable systemd-networkd-wait-online
  - name: 'enable systemd-networkd-wait-online.service if not enabled'
    shell: |
      if ! systemctl is-enabled systemd-networkd-wait-online.service ; then
          systemctl enable systemd-networkd-wait-online.service
      fi


  # enable fstrim service
  - name: 'enable fstrim.service if not enabled'
    shell: |
      if ! systemctl is-enabled fstrim.service ; then
          systemctl enable fstrim.service
      fi

