---
ferm__enabled: True

ferm__host_rules:

  # jupyter port archbtw (tcp)
  - name: 'DEBOPS_accept_8888_jupyter_tcp_archbtw'
    type: 'accept'
    accept_any: False
    saddr: '10.10.100.10'
    daddr: '10.10.120.96'
    dport: '8888'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from archbtw to port 8888/tcp'

  # jupyter port mbp (tcp)
  - name: 'DEBOPS_accept_8888_jupyter_tcp_mbp'
    type: 'accept'
    accept_any: False
    saddr: '10.10.100.20'
    daddr: '10.10.120.96'
    dport: '8888'
    protocol: 'tcp'
    rule_state: 'present'
    comment: 'accept incoming connections from mbp to port 8888/tcp'

