---
resources__host_paths:

  # opt dir
  - path: '/opt'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
    acl:
      - etype: 'user'
        entity: 'tautulli'
        permissions: 'rwx'
        state: 'present'

  # tautulli dir
  - path: '/opt/tautulli'
    owner: 'tautulli'
    group: 'tautulli'
    mode: '0700'
    state: 'directory'
    acl:
      - etype: 'user'
        entity: 'fclaude'
        permissions: 'rwx'
        state: 'present'

resources__host_files:

  # tautulli systemd service file
  - src: '{{ resources__src + ansible_hostname + "/etc/systemd/system/tautulli.service" }}'
    dest: '/etc/systemd/system/tautulli.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'present'


resources__host_repositories:

  # tautulli repository
  - repo: 'https://github.com/tautulli/tautulli'
    dest: '/opt/tautulli'
    owner: 'tautulli'
    _update: false
    acl:
      - etype: 'user'
        entity: 'fclaude'
        permissions: 'rwx'
        state: 'present'

# resources__host_commands:

# # tautulli systemd actions

#   - name: 'reload systemd daemon'
#     shell: |
#       systemctl daemon-reload
#     # state: 'ignore'

#   - name: 'sleep for a few seconds'
#     shell: |
#       sleep 2
#     # state: 'ignore'

#   - name: 'disable systemd tautulli service'
#     shell: |
#       systemctl disable tautulli.service
#     # state: 'ignore'

#   - name: 'sleep for a few seconds'
#     shell: |
#       sleep 2
#     # state: 'ignore'

#   - name: 'enable systemd tautulli service'
#     shell: |
#       systemctl enable tautulli.service
#     # state: 'ignore'

#   - name: 'sleep for a few seconds'
#     shell: |
#       sleep 2
#     # state: 'ignore'

#   - name: 'start systemd tautulli service if disabled'
#     shell: |
#       if ! systemctl is-active tautulli.service ; then
#           systemctl start tautulli.service
#       fi
#     # state: 'ignore'