---
apt__host_repositories:

## OFFICIAL MONO REPO
  - repo: 'deb https://download.mono-project.com/repo/debian stable-buster main'
    architecture: 'amd64'
    filename: 'mono-official-stable'
    distribution: 'Debian'
    state: 'present'

apt__host_keys:

## OFFICIAL MONO REPO KEY
  - keyserver: 'hkp://keyserver.ubuntu.com:80'
    distribution: 'Debian'
    id: '3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    state: 'present'
    architecture: 'amd64'
