---
apt__host_repositories:

  # official mono repo
  - repo: 'deb https://download.mono-project.com/repo/debian stable-buster main'
    architecture: 'amd64'
    filename: 'mono-official-stable'
    distribution: 'Debian'
    state: 'present'

apt__host_keys:

  # official mono repo key
  - keyserver: 'hkps://keyserver.ubuntu.com:443'
    distribution: 'Debian'
    id: '3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    state: 'present'
    architecture: 'amd64'
