---
nfs__host_shares:

  # truenas tv
  - path: '/mnt/nfs/music'
    src: '10.10.70.20:/mnt/tank03/ds01/media/music'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd_no_timeo }}"
    owner: 'fclaude'
    group: 'labmedia'
    mode: '0750'
    state: 'present'

  # nzbget to lidarr share
  - path: '/mnt/nfs/nzbget'
    src: '10.10.90.12:/lidarr'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd_no_timeo }}"
    owner: '158'
    group: 'labmedia'
    mode: '0750'
    state: 'present'

  # rtps share
  - path: '/mnt/nfs/rt_work'
    src: '10.10.90.10:/rt_work'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd_no_timeo }}"
    owner: '2020'
    group: '2030'
    mode: '0750'
    state: 'present'