---
nfs__host_shares:

  # truenas books (read/write)
  - path: '/mnt/nfs/common'
    src: '10.10.70.20:/mnt/tank03/ds02/lab/common'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd_med_timeo }}"
    owner: 'fclaude'
    group: 'labmedia'
    mode: '0750'
    state: 'present'

