---
cron__crontab_host_jobs:

  # run instaloader script every 6 hours
  - name: 'instaloader_script_6hour'
    user: 'insta-dl'
    special_time: '0 */6 * * *'
    job: '/home/insta-dl/instaloader.sh'
    state: 'absent'
    disabled: false
