---
nfs__host_shares:

  ## truenas nextcloud
  - path: '/mnt/nfs/nextcloud'
    src: '10.10.70.20:/mnt/tank03/ds03/nextcloud'
    fstype: 'nfs4'
    opts: "{{ nfs_opts.def_rw + nfs_opts.safety + nfs_opts.systemd_no_timeo }}"
    owner: 'www-data'
    group: 'www-data'
    mode: '0770'
    state: 'present'
