---
nginx__default_servers: []

nginx__internal_servers: []

owncloud__nginx__dependent_servers:

  ## https://docs.nextcloud.com/server/17/admin_manual/installation/nginx.html
  ## Corresponds to 65ff129d27a912a27c0b4ebe42b2c59df262b72a
  ## from https://github.com/nextcloud/documentation.git
  - type: 'default'
    ssl: False
    enabled: True
    by_role: 'debops.owncloud'
    filename: 'nextcloud'
    name: '{{ owncloud__fqdn }}'
    root: '{{ owncloud__deploy_path }}'
    webroot_create: False
    deny_hidden: False
    ## Nextcloud has its own maintenance page
    maintenance: False

    ## https://docs.nextcloud.com/server/17/admin_manual/issues/general_troubleshooting.html#common-problems-error-messages
    ## DebOps default should be fine.
    # keepalive: '3600'

    robots_tag: [ 'none' ]
    permitted_cross_domain_policies: 'none'
    frame_options: '{{ omit if (owncloud__variant == "nextcloud" and
                                owncloud__release is version("17.0", "<"))
                            else "SAMEORIGIN" }}'

    options: |
      add_header X-Download-Options noopen;

      # Set max upload size.
      client_max_body_size {{ owncloud__upload_size }};
      {% if owncloud__nginx_client_body_temp_path %}
      client_body_temp_path '{{ owncloud__nginx_client_body_temp_path }}';
      {% endif %}
      fastcgi_buffers 64 4K;

      {% if owncloud__app_user_webfinger_support | bool %}
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
      {% endif %}

      {% if owncloud__variant == "nextcloud" %}
      # Enable gzip but do not remove ETag headers
      gzip on;
      gzip_vary on;
      gzip_comp_level 4;
      gzip_min_length 256;
      gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
      gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
      {% else %}
      # Disable gzip to avoid the removal of the ETag header
      gzip off;
      {% endif %}

      # Uncomment if your server is build with the ngx_pagespeed module
      # This module is currently not supported.
      #pagespeed off;

      error_page            403             /core/templates/403.php;
      error_page            404             /core/templates/404.php;


      # Avoid to send the security headers twice as ownCloud
      # also adds the X-* HTTP headers.
      fastcgi_param modHeadersAvailable true;

    location_list:
      - pattern: '= /robots.txt'
        options: |
          log_not_found off;

      - pattern: '= /.well-known/carddav'
        options: |
          return 301 $scheme://$host/remote.php/dav;

      - pattern: '= /.well-known/caldav'
        options: |
          return 301 $scheme://$host/remote.php/dav;

      - pattern: '= /'
        options: |
          ## Not used in the Nginx configuration example of ownCloud.
          ## Needed because `security.limit_extensions` defaults to `.php` in DebOps.
          rewrite ^ /index.php;

      - pattern: '/'
        options: |
          rewrite ^ /index.php;

      - pattern: '~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/'
        options: |
          deny all;

      - pattern: '~ ^\/(?:\.|autotest|occ|issue|indie|db_|console)'
        options: |
          deny all;

      - pattern: '~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy)\.php(?:$|\/)'
        options: |
          include fastcgi_params;
          fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
          set $path_info $fastcgi_path_info;
          try_files $fastcgi_script_name =404;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $path_info;
          fastcgi_param HTTPS on;
          #Avoid sending the security headers twice
          fastcgi_param modHeadersAvailable true;
          # Enable pretty urls
          fastcgi_param front_controller_active true;
          fastcgi_intercept_errors on;
          {% if (ansible_local.nginx.version
                 if (ansible_local|d() and ansible_local.nginx|d() and
                     ansible_local.nginx.version|d())
                 else "0.0")
                is version_compare("1.7.11",'>=') %}
          fastcgi_request_buffering off;
          {% endif %}

          fastcgi_pass php_owncloud;

          fastcgi_read_timeout {{ owncloud__timeout }};

      - pattern: '~ ^\/(?:updater|oc[ms]-provider)(?:$|\/)'
        options: |
          try_files $uri/ =404;
          index index.php;

      - pattern: '~ \.(?:css|js|woff2?|svg|gif|map)$'
        options: |
          # Adding the cache control header for js, css and map files
          # Make sure it is BELOW the PHP block

          try_files $uri /index.php$request_uri;
          add_header Cache-Control "public, max-age=15778463";

          add_header X-Content-Type-Options nosniff;
          add_header X-Download-Options noopen;
          {% if not (owncloud__variant == "nextcloud" and
                     owncloud__release is version("17.0", "<")) %}
          add_header X-Frame-Options "SAMEORIGIN";
          {% endif %}
          add_header X-Permitted-Cross-Domain-Policies none;
          add_header X-Robots-Tag none;
          add_header X-XSS-Protection "1; mode=block";

          {% if not (owncloud__nginx_access_log_assets|bool) %}
          access_log off;
          {% endif %}

      - pattern: '~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap|mp4|webm)$'
        options: |
          try_files $uri /index.php$request_uri;

          {% if not (owncloud__nginx_access_log_assets|bool) %}
          access_log off;
          {% endif %}

    ## Not used so that the exact order of locations from the upstream nginx example can be used.
    # type: 'php'
    # php_upstream: 'php_owncloud'
    # php_limit_except: False
    # php5_location: '^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/)'
    # php_options: |
    #   fastcgi_read_timeout {{ owncloud__timeout }};