---
resources__host_paths:

  # create root mount dirs
  - path: '/mnt'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  - path: '/mnt/nfs'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

  # nextcloud home
  - path: '/srv/www/nextcloud'
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'
    state: 'directory'

resources__host_files:

  - path: '/etc/nginx/sites-enabled/localhost.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-available/localhost.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-enabled/welcome.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-available/welcome.conf'
    state: 'absent'

  - path: '/etc/nginx/sites-enabled/default'
    state: 'absent'

  - path: '/etc/nginx/sites-available/default'
    state: 'absent'